# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import python_executor_pb2 as python__executor__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in python_executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonExecutorServiceStub(object):
    """PythonExecutorService defines the gRPC contract between Go PE and the Python process.
    The Python process is the gRPC SERVER, Go PE is the CLIENT.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteStream = channel.stream_stream(
                '/wso2.gateway.python.v1.PythonExecutorService/ExecuteStream',
                request_serializer=python__executor__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=python__executor__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/wso2.gateway.python.v1.PythonExecutorService/HealthCheck',
                request_serializer=python__executor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=python__executor__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PythonExecutorServiceServicer(object):
    """PythonExecutorService defines the gRPC contract between Go PE and the Python process.
    The Python process is the gRPC SERVER, Go PE is the CLIENT.
    """

    def ExecuteStream(self, request_iterator, context):
        """Bidirectional stream for executing policies.
        Go sends ExecutionRequest, Python responds with ExecutionResponse.
        Each request has a unique request_id that the response must echo back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for readiness.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=python__executor__pb2.ExecutionRequest.FromString,
                    response_serializer=python__executor__pb2.ExecutionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=python__executor__pb2.HealthCheckRequest.FromString,
                    response_serializer=python__executor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wso2.gateway.python.v1.PythonExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wso2.gateway.python.v1.PythonExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonExecutorService(object):
    """PythonExecutorService defines the gRPC contract between Go PE and the Python process.
    The Python process is the gRPC SERVER, Go PE is the CLIENT.
    """

    @staticmethod
    def ExecuteStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/wso2.gateway.python.v1.PythonExecutorService/ExecuteStream',
            python__executor__pb2.ExecutionRequest.SerializeToString,
            python__executor__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wso2.gateway.python.v1.PythonExecutorService/HealthCheck',
            python__executor__pb2.HealthCheckRequest.SerializeToString,
            python__executor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
